name: Comntinuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    # setup-nodeが正常に機能しないので無効化しておく
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 12.x
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test

  # TODO: master push時に適当なファイルをartifactとしてupload
  on-push-master:
    name: Event push master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Temporal
        run: |
          echo ${{ github.event }}