name: Comntinuous Integration
on: push

jobs:
  unit-test:
    name: Unit Testt
    runs-on: ubuntu-latest
    # setup-nodeが正常に機能しないので無効化しておく
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 12.x
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test

