name: Coverage test
on: pull_request

jobs:
  test-cov-report:
    name: Test code coverage report
    runs-on: ubuntu-latest
    env:
      # TODO: パラメータの二重メンテは面倒なので、workspace-coverageはなくす(こちらで統一する)
      PARAMS:
        -v --root ./sample1 --ignore-tests -o Html Lcov --output-dir .
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.13.3'
          args: ${{env.PARAMS}}

      - name: Download coverage file (in artifact) for comparison
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: workflow_pushed_master.yml
          branch: master
          path: base_coverage
          name: my-artifact

      - name: Apply code coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./lcov.info
          lcov-base: base_coverage/lcov.info

  test-download-artifact:
    name: Download coverage artifact
    runs-on: ubuntu-18.04
    if: false
    steps:
      - name: download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: workflow_pushed_master.yml
          #commit: ${{ github.event.pull_request.base.sha }}
          branch: master
          path: base_coverage
          name: my-artifact

      - name: show artifact
        run: |
          find base_coverage -type f
