name: Hello World!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Github Actions!"
  
  check-tmate:
    name: Check tmate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.5
