name: Sample for using composite run steps action
on: push

env:
    # TODO: dockerで定義している変数と同期
    SNPE_VERSION: 1.42
    CARGO_TARGET_DIR: /work/chart-edge-ai/target

jobs:
  test-composite:
    name: Test composite run steps action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run composite
        uses: ./.github/actions/composite-test
        with:
          who-to-greet: test-composite
      - name: Run composite 2nd
        uses: ./.github/actions/composite-test
        with:
          who-to-greet: test-composite
          flag: false
  test-install-components:
    name: Test composite run steps action (install-components)
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: |
        /work/chart-edge-ai/snpe-rs/snpe-sys/snpe-c-api/external/snpe_${{env.SNPE_VERSION}}/lib/x86_64-linux-clang:
        ${{env.CARGO_TARGET_DIR}}/debug
    steps:
      - uses: actions/checkout@v2
      - name: Show LD_LIBRARY_PATH
        run: echo $LD_LIBRARY_PATH

      - name: Run install-components
        uses: ./.github/actions/install-components
        with:
          additional-apt-pkg: libopencv-dev
      
      - name: test cargo
        working-directory: /work/sample1
        run: |
          cargo --version
          cargo test
