name: Sample for using composite run steps action
on: push

jobs:
  test-composite:
    name: Test composite run steps action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run composite
        uses: ./.github/actions/composite-test
        with:
          who-to-greet: test-composite
  test-install-components:
    name: Test composite run steps action (install-components)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install-components
        uses: ./.github/actions/install-components
        with:
          additional-apt-pkg: libopencv-dev
