name: Sample for using composite run steps action
on: push

jobs:
  test-composite:
    name: Test composite run steps action
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"

      - name: Run composite
        uses: ./.github/actions/composite-test
